"""Plot the LLMflation / price-capability data from collected snapshots.

  python3 -m beacon.plot

Behavior depends on how much history exists:
- 1 snapshot  -> price-capability FRONTIER (cheapest $/Mtok to reach each GPQA
  tier today): one frozen frame of the LLMflation curve.
- >=2 snapshots -> the real LLMflation TIME SERIES (iso-quality price per tier
  over snapshot dates).

Outputs an SVG (open in any browser) and an ASCII chart to the terminal.
Dependency-free: SVG is generated by hand, no matplotlib.
"""
import json
import math
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

from beacon import analyze, index

PLOTS_DIR = analyze.DATA_DIR.parent / "plots"


# ---- pure data shaping (unit-tested) ----------------------------------------

def frontier_curve(
    listings: List[dict], cap: Dict[str, Dict[str, float]], benchmark: str,
    thresholds: Sequence[float],
) -> List[Tuple[float, Optional[float]]]:
    """Cheapest blended price to reach each capability threshold (iso-quality)."""
    pairs = analyze.join_prices_to_scores(listings, cap, benchmark)
    return [(t, index.iso_quality(pairs, t)) for t in thresholds]


def iso_quality_series(
    snapshots: Sequence[Tuple[str, List[dict]]],
    cap: Dict[str, Dict[str, float]], benchmark: str, threshold: float,
) -> List[Tuple[str, float]]:
    """Iso-quality price for one tier across dated snapshots, sorted by date."""
    out = []
    for date, listings in snapshots:
        pairs = analyze.join_prices_to_scores(listings, cap, benchmark)
        iso = index.iso_quality(pairs, threshold)
        if iso is not None:
            out.append((date, iso))
    return sorted(out)


def scored_points(
    listings: List[dict], cap: Dict[str, Dict[str, float]], benchmark: str
) -> List[Tuple[str, float, float]]:
    """(model, capability, blended_price) for every listing that has a score."""
    pts = []
    for li in listings:
        scores = cap.get(li["model"])
        if scores and benchmark in scores:
            pts.append((li["model"], scores[benchmark], li["blended_mtok"]))
    return pts


# ---- ASCII rendering (presentation) -----------------------------------------

def render_ascii_frontier(points, frontier, benchmark, width=58, height=16):
    xs = [c for _, c, _ in points]
    ys = [p for _, _, p in points]
    xmin, xmax = min(xs), max(xs)
    ly = [math.log10(p) for p in ys]
    ymin, ymax = min(ly), max(ly)

    def col(c):
        return int((c - xmin) / (xmax - xmin) * (width - 1)) if xmax > xmin else 0

    def row(p):  # row 0 = top = most expensive
        lp = math.log10(p)
        return int((ymax - lp) / (ymax - ymin) * (height - 1)) if ymax > ymin else 0

    grid = [[" "] * width for _ in range(height)]
    # scatter all scored models as '.'
    for _, c, p in points:
        grid[row(p)][col(c)] = "."
    # frontier (cheapest at each threshold) as '*'
    for t, iso in frontier:
        if iso is not None and xmin <= t <= xmax:
            grid[row(iso)][col(t)] = "*"

    out = [f"  price $/Mtok (log)   * = cheapest-to-reach frontier   . = a model"]
    for r in range(height):
        # y label at top, mid, bottom
        if r == 0:
            lab = f"{10**ymax:7.1f}"
        elif r == height - 1:
            lab = f"{10**ymin:7.2f}"
        elif r == height // 2:
            lab = f"{10**((ymax+ymin)/2):7.2f}"
        else:
            lab = " " * 7
        out.append(f"{lab} |" + "".join(grid[r]))
    out.append(" " * 8 + "+" + "-" * width)
    out.append(" " * 9 + f"{xmin:<5.0f}" + " " * (width - 12) + f"{xmax:>5.0f}")
    out.append(" " * 8 + f"  {benchmark} capability score ->")
    return "\n".join(out)


def render_ascii_series(series_by_tier, width=54):
    lines = ["  LLMflation time series (iso-quality $/Mtok per tier):"]
    for name, series in series_by_tier.items():
        if not series:
            continue
        spark = " ".join(f"{d[5:]}:${v:.3f}" for d, v in series)
        lines.append(f"   {name:<12} {spark}")
    return "\n".join(lines)


# ---- SVG rendering (presentation) -------------------------------------------

def _svg_frontier(points, frontier, benchmark, w=820, h=520):
    pad = 70
    xs = [c for _, c, _ in points]
    xmin, xmax = min(xs), max(xs)
    ly = [math.log10(p) for _, _, p in points]
    ymin, ymax = math.floor(min(ly)), math.ceil(max(ly))

    def px(c):
        return pad + (c - xmin) / (xmax - xmin) * (w - 2 * pad)

    def py(p):
        lp = math.log10(p)
        return h - pad - (lp - ymin) / (ymax - ymin) * (h - 2 * pad)

    e = ['<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" '
         'font-family="ui-sans-serif,system-ui,sans-serif">' % (w, h)]
    e.append('<rect width="100%%" height="100%%" fill="#0b0e14"/>')
    e.append('<text x="%d" y="32" fill="#e6e6e6" font-size="18" font-weight="600">'
             'Beacon: price-capability frontier (one frame of the LLMflation curve)</text>'
             % pad)
    # log gridlines
    for d in range(ymin, ymax + 1):
        y = py(10 ** d)
        e.append('<line x1="%d" y1="%.1f" x2="%d" y2="%.1f" stroke="#1e2633"/>'
                 % (pad, y, w - pad, y))
        e.append('<text x="%d" y="%.1f" fill="#7a8699" font-size="11" text-anchor="end">'
                 '$%s</text>' % (pad - 8, y + 4, _money(10 ** d)))
    # x ticks
    for c in range(int(xmin // 10 * 10), int(xmax) + 1, 10):
        if c < xmin:
            continue
        x = px(c)
        e.append('<text x="%.1f" y="%d" fill="#7a8699" font-size="11" '
                 'text-anchor="middle">%d</text>' % (x, h - pad + 20, c))
    # frontier line
    fr = [(px(t), py(v)) for t, v in frontier if v is not None]
    if fr:
        d = "M" + " L".join("%.1f %.1f" % xy for xy in fr)
        e.append('<path d="%s" fill="none" stroke="#f5a623" stroke-width="2.5"/>' % d)
    # scatter
    for model, c, p in points:
        e.append('<circle cx="%.1f" cy="%.1f" r="3.5" fill="#4aa3ff" opacity="0.85"/>'
                 % (px(c), py(p)))
    # axis labels
    e.append('<text x="%d" y="%d" fill="#9aa7b8" font-size="13" text-anchor="middle">'
             '%s capability score -></text>' % (w // 2, h - 18, benchmark))
    e.append('<text x="20" y="%d" fill="#9aa7b8" font-size="13" '
             'transform="rotate(-90 20 %d)">price $/Mtok (log) -- lower is cheaper</text>'
             % (h // 2, h // 2))
    e.append('<text x="%d" y="56" fill="#f5a623" font-size="12">orange = cheapest '
             'price to reach each capability (iso-quality frontier)</text>' % pad)
    e.append("</svg>")
    return "\n".join(e)


def _money(v):
    return ("%.2f" % v).rstrip("0").rstrip(".") if v < 10 else "%.0f" % v


# ---- CLI --------------------------------------------------------------------

def _load_snapshots():
    out = []
    for p in sorted(analyze.SNAPSHOT_DIR.glob("*.json")):
        snap = json.loads(p.read_text())
        out.append((snap["observed_at"], snap["listings"]))
    return out


def main() -> int:
    snapshots = _load_snapshots()
    if not snapshots:
        print("No snapshots. Run: python3 -m beacon.collector")
        return 1
    rows = analyze.read_benchmarks(str(analyze.BENCHMARKS_CSV))
    cap = analyze.build_capability_map(rows, include_unverified=False)
    if not cap:
        print("No verified benchmark scores in data/benchmarks.csv — calibrate first.")
        return 1

    PLOTS_DIR.mkdir(exist_ok=True)
    bench = "GPQA-Diamond"

    if len(snapshots) >= 2:
        tiers = {"frontier(>=90)": 90, "strong(>=70)": 70, "gpt-4-class(>=50)": 50}
        series_by_tier = {
            name: iso_quality_series(snapshots, cap, bench, thr)
            for name, thr in tiers.items()
        }
        print(render_ascii_series(series_by_tier))
        print(f"\n(time-series SVG for {len(snapshots)} snapshots — extend _svg as needed)")
        return 0

    # Single snapshot: the price-capability frontier (one frame).
    date, listings = snapshots[0]
    points = scored_points(listings, cap, bench)
    cmin = int(min(c for _, c, _ in points))
    cmax = int(max(c for _, c, _ in points))
    thresholds = list(range(cmin, cmax + 1, 5))
    frontier = frontier_curve(listings, cap, bench, thresholds)

    print(f"Snapshot {date}: {len(points)} models scored on {bench}.")
    print(f"Only 1 snapshot on disk -> drawing the price-capability FRONTIER")
    print(f"(the LLMflation curve needs >=2 dated snapshots; it accrues daily).\n")
    print(render_ascii_frontier(points, frontier, bench))

    svg_path = PLOTS_DIR / f"frontier-{date}.svg"
    svg_path.write_text(_svg_frontier(points, frontier, bench))
    print(f"\nSVG written -> {svg_path}")
    print("Open it with:  open " + str(svg_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
